replicaCount: 1

image:
  repository: springboot-app
  tag: local
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30007

containerPort: 8080

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []

