name: run reusable workflow
on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
                default: test
            deployment:
                required: true
                type: string
            build_code:
                required: true
                type: string
                
jobs:

 print_input:
    name: print inputvalues
    runs-on: ubuntu-latest
    steps:
        - name: input-values
          shell: 'bash'
          id: get-input
          run: |
            echo "environment   =${{inputs.environment}}"      
            echo "Deployment   =${{inputs.deployment}}"   
            echo "Build_code   =${{inputs.build_code}}"               
 
 run-shell-command:
    name: Run shell command
    runs-on: ubuntu-latest
    steps:
       - name: Echo a string
         run: echo "Hello this is a first job"
       - name: Run a pipeleine
         run: echo "This iakanvsdvmsdlkvm s"
