name: CD Main Workflow

on:
  workflow_call:
    inputs:
      build_code:
        type: string
        default: true
      build_docker:
        type: string
        default: true
      codeql:
        type: string
        default: true
      deploy:
        type: string
        default: true
      image_tag:
        type: string
        required: true
      image_name:
        type: string
        default: commitbooking
      fallback_image:
        type: string
        default: nginx
      helm_chart_path:
        type: string
        default: ./demo
      helm_release_name:
        type: string
        default: demo

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --------------------
      # Build Code
      # --------------------
      - name: Setup JDK 17
        if: ${{ inputs.build_code == 'true' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Code
        if: ${{ inputs.build_code == 'true' }}
        run: |
          echo "Building Java application..."
          mvn clean package -DskipTests
          echo "Build completed ✅"

      # --------------------
      # Docker
      # --------------------
      - name: Docker Build   and Install Kind cluster
        if: ${{ inputs.build_docker == 'true' }}
        run: |
          IMAGE="${{ inputs.image_name }}:${{ inputs.image_tag }}"
          echo "Building Docker image: $IMAGE"
          docker build -t $IMAGE .
          echo "FINAL_IMAGE=$IMAGE" >> $GITHUB_ENV
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --wait 60s
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/           

      - name: Use Fallback Image
        if: ${{ inputs.build_docker != 'true' }}
        run: |
          IMAGE="${{ inputs.fallback_image }}:${{ inputs.image_tag }}"
          echo "Using fallback image: $IMAGE"
          echo "FINAL_IMAGE=$IMAGE" >> $GITHUB_ENV

      # --------------------
      # CodeQL
      # --------------------
      - name: Initialize CodeQL
        if: ${{ inputs.codeql == 'true' }}
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Perform CodeQL Analysis
        if: ${{ inputs.codeql == 'true' }}
        uses: github/codeql-action/analyze@v3

      # --------------------
      # Helm Deploy
      # --------------------
      - name: Deploy with Helm
        if: ${{ inputs.deploy == 'true' }}
        run: |
          echo "Deploying Helm release: ${{ inputs.helm_release_name }}"
          echo "Using image: $FINAL_IMAGE"
          helm upgrade --install ${{ inputs.helm_release_name }} \
            ${{ inputs.helm_chart_path }} \
            --set image.repository=$(echo $FINAL_IMAGE | cut -d: -f1) \
            --set image.tag=$(echo $FINAL_IMAGE | cut -d: -f2)
