name: Build and Deploy to KinD

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

    - name: Setup KinD
      uses: helm/kind-action@v1.7.0

    - name: Load Docker image into KinD
      run: |
        kind load docker-image ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

    - name: Deploy to KinD
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/springboot-app
        kubectl get all



















# name: run reusable workflow
# on:
#     workflow_call:
#         inputs:
#             environment:
#                 required: true
#                 type: string
#                 default: test
#             deployment:
#                 required: true
#                 type: string
#             build_code:
#                 required: true
#                 type: string
                
# jobs:

#  print_input:
#     name: print inputvalues
#     runs-on: ubuntu-latest
#     steps:
#         - name: input-values
#           shell: 'bash'
#           id: get-input
#           run: |
#             echo "environment   =${{inputs.environment}}"      
#             echo "Deployment   =${{inputs.deployment}}"   
#             echo "Build_code   =${{inputs.build_code}}"               
 
#  run-shell-command:
#     name: Run shell command
#     runs-on: ubuntu-latest
#     steps:
#        - name: Echo a string
#          run: echo "Hello this is a first job"
#        - name: Run a pipeleine
#          run: echo "This iakanvsdvmsdlkvm s"
